package com.stocks.standalone;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import java.util.Properties;

import com.stocks.util.Utility;

public class GoogleStockScreener {
//	final static String MKT_CAP_FROM = "750000000";
//	final static String MKT_CAP_TO   = "9723390000000";
//	final static String DIV_YIELD_FROM = "5%";
//	final static String DIV_YIELD_TO = "100%";
//	
//	final static String GOOGLE_URL = "http://www.google.com/finance?output=json&start=0&num=5000&noIL=1&q=[currency%20%3D%3D%20%22USD%22%20%26%20%28%28exchange%20%3D%3D%20%22NYSEARCA%22%29%20%7C%20%28exchange%20%3D%3D%20%22NYSEAMEX%22%29%20%7C%20%28exchange%20%3D%3D%20%22NYSE%22%29%20%7C%20%28exchange%20%3D%3D%20%22NASDAQ%22%29%29%20%26%20%28market_cap%20%3E%3D%20" +MKT_CAP_FROM+ "%29%20%26%20%28market_cap%20%3C%3D%20" +MKT_CAP_TO+ "%29%20%26%20%28dividend_yield%20%3E%3D%20" +DIV_YIELD_FROM+ "29%20%26%20%28dividend_yield%20%3C%3D%20" +DIV_YIELD_TO+ "29%20]&restype=company&ei=CrpHUditA4myqgHD_AE";

	public static void main(final String... args) throws Exception{
		final Properties properties = new Properties();
		try{
			properties.load( IntraDayDataProcessor.class.getResourceAsStream(args[0]) );
		}
		catch(Exception e){
			System.out.println("Usage: GoogleStockScreener <properties file>.\nException in loading properties: " +args);
			e.printStackTrace();
			return;
		}

		final String content = Utility.getContent( properties.getProperty("google.stock.screener.url") );
		final List<String> symbols = new ArrayList<String>();
		for( String line : content.split("\n") ){
			if( line.startsWith("\"ticker\"") ){
				String symbol = line.substring( 12, line.indexOf("\",") );
				if( symbol.indexOf("-") == -1 && symbol.indexOf(".") == -1 ){
					symbols.add( symbol );
				}
			}
		}
		System.out.println( "Total " +symbols.size()+ " symbols pulled from Google Stock Screener." );
		System.out.println( "All symbols: " +symbols );

		final List<String> amexList = new ArrayList(Arrays.asList("AAMC,AAU,ACCU,ACU,ACWV,ACY,ADGE,ADK,ADK-A,AE,AFK,AGA,AGEM,AGF,AGG,AGLS,AGOL,AGQ,AGX,AGZ,AIA,AJB,AKG,ALD,ALFA,ALN,ALTL,ALTV,AMCO,AMJ,AMLP,AMPE,AMPS,AMS,AMU,AND,ANGL,ANV,AOA,AOK,AOM,AOR,API,APP,APT,APTS,AQQ,ARGT,ARR.W,ASEA,ASM,ATL,ATMP,AUD,AUMN,AUNZ,AUSE,AVL,AWX,AXDI,AXHE,AXJL,AXN,AXTE,AXU,AXX,AYT,AZC,AZIA,BAA,BAB,BABS,BABZ,BAL,BBH,BBRC,BCM,BCV,BDCL,BDCS,BDD,BDR,BFOR,BFY,BHB,BHV,BIK,BIL,BIR-A,BIV,BIZD,BJK,BKF,BKJ,BKLN,BKR,BLE,BLJ,BLV,BND,BNO,BOIL,BOND,BONE,BPS,BQY,BRAF,BRAQ,BRAZ,BRD,BRF,BRN,BRXX,BRZS,BRZU,BSCD,BSCE,BSCF,BSCG,BSCH,BSCI,BSCJ,BSCK,BSCL,BSCM,BSJD,BSJE,BSJF,BSJG,BSJH,BSJI,BSJJ,BSJK,BSV,BTG,BTI,BTN,BTX,BUND,BUNT,BVX,BWL.A,BWX,BWZ,BXE,BZC,BZF,BZM,BZQ,CAD,CAFE,CAK,CANE,CAPE,CAW,CBND,CCA,CCF,CCXE,CDY,CEF,CEMB,CEP,CET,CEV,CEW,CFD,CFP,CFT,CGR,CGW,CH,CHEP,CHGS,CHIE,CHII,CHIM,CHIQ,CHIX,CHLC,CHOC,CHXX,CIK,CIU,CIX,CLM,CLY,CMBS,CMDT,CMF,CMFO,CMT,CNDA,CNPF,CNR,CNY,COBO,COLX,COPX,CORN,CORP,COVR,COW,CPHI,CPI,CQP,CQQQ,CRBQ,CRF,CRM.W,CRMD,CROC,CROP,CRUD,CRV,CRVP,CSCB,CSCR,CSD,CSJ,CSLS,CSM,CSMA,CSMB,CSMN,CTF,CTO,CTP,CUO,CUR,CURE,CUT,CVM,CVOL,CVR,CVU,CVY,CWB,CWI,CXA,CXM,CYB,CZA,DAG,DBA,DBB,DBBR,DBC,DBE,DBEF,DBEM,DBGR,DBIZ,DBJP,DBO,DBP,DBS,DBU,DBV,DCNG,DDM,DDP,DEF,DEJ,DEM,DES,DEW,DFE,DFF,DFJ,DGAZ,DGL,DGLD,DGP,DGS,DGSE,DGT,DGZ,DHS,DHY,DIA,DIG,DIM,DIRT,DIT,DIV,DJCI,DJP,DLA,DLBL,DLBS,DLN,DLS,DMF,DNL,DNN,DNO,DOD,DOG,DOIL,DOL,DON,DOO,DPK,DPU,DPW,DRN,DRR,DRV,DRW,DSI,DSLV,DSS,DSUM,DTD,DTH,DTN,DTO,DTUS,DTYL,DTYS,DUG,DUST,DVHI,DVY,DVYA,DVYE,DVYL,DWAS,DWM,DWTI,DWX,DXD,DXJ,DXR,DYY,DZK,DZZ,EAD,EAPS,EBND,ECF,ECH,ECNS,ECON,EDC,EDEN,EDIV,EDV,EDZ,EEB,EEH,EEHB,EELV,EEM,EEMS,EEMV,EES,EET,EEV,EFA,EFAV,EFG,EFNL,EFO,EFU,EFV,EFZ,EGAS,EGI,EGPT,EIA,EIDO,EIM,EIO,EIP,EIRL,EIS,EIV,ELD,ELLO,ELMD,EMAN,EMB,EMCD,EMCR,EMDD,EMDG,EMFT,EMHD,EMHY,EMI,EMJ,EMLC,EMLP,EMT,EMXX,ENGN,ENOR,ENX,ENY,ENZL,EOX,EPHE,EPI,EPM,EPM-A,EPOL,EPP,EPS,EPU,EPV,EQL,ERB,ERC,ERH,ERO,ERUS,ERX,ERY,ESP,ESR,ESTE,ETAK,ETF,ETUA,ETUB,EUFX,EUM,EUO,EUSA,EVBN,EVI,EVJ,EVK,EVM,EVO,EVP,EVV,EVX,EVY,EWA,EWAS,EWC,EWCS,EWD,EWEM,EWG,EWGS,EWH,EWHS,EWI,EWJ,EWK,EWL,EWM,EWN,EWO,EWP,EWQ,EWRI,EWRM,EWRS,EWS,EWSS,EWT,EWU,EWUS,EWV,EWW,EWX,EWY,EWZ,EWZS,EXE,EXI,EXT,EZA,EZJ,EZM,EZU,FAB,FAD,FAN,FAS,FAUS,FAX,FAZ,FBG,FBT,FCA,FCAN,FCG,FCO,FCSC,FDD,FDL,FDM,FDN,FDT,FDTS,FEEU,FEM,FEMS,FEN,FEP,FEU,FEX,FEZ,FFR,FGD,FGEM,FGM,FHK,FIEU,FIGY,FINU,FINZ,FIVZ,FIW,FJP,FKU,FLAG,FLM,FLN,FLOT,FLRN,FLTR,FM,FMF,FMK,FNDA,FNDB,FNDC,FNDE,FNDF,FNDX,FNI,FNIO,FNK,FNX,FNY,FOL,FORX,FPA,FPE,FPP,FPP.W,FPX,FRAK,FRD,FRI,FRN,FRS,FSE,FSG,FSI,FSP,FSZ,FTA,FTC,FTF,FTY,FU,FUD,FVD,FVI,FVL,FWDB,FXA,FXB,FXC,FXD,FXE,FXF,FXG,FXH,FXI,FXL,FXN,FXO,FXP,FXR,FXS,FXU,FXY,FXZ,FYC,FYT,FYX,GAF,GAL,GASL,GASX,GAZ,GBB,GBF,GBR,GCC,GCE,GDAY,GDX,GDXJ,GEX,GGEM,GGGG,GGN,GGN-B,GGOV,GHM,GHYG,GIG,GII,GLD,GLDX,GLL,GLO,GLOW,GLQ,GLTR,GLU,GLU-A,GLV,GMF,GML,GMM,GMO,GNAT,GNR,GORO,GOVT,GPL,GRC,GREK,GRES,GRF,GRH,GRH-C,GRI,GRU,GSB,GSC,GSG,GSP,GSRA,GSS,GST,GST-A,GSV,GSY,GTAA,GTE,GTIP,GTT,GTU,GUNR,GUR,GURU,GV,GVI,GVP,GWL,GWX,GXC,GXF,GXG,GYLD,HAO,HAP,HDG,HDGE,HDGI,HDV,HEB,HECO,HEDJ,HGEM,HGI,HH,HILO,HLM.P,HNW,HSPX,HTM,HUSA,HUSE,HVPW,HYD,HYEM,HYG,HYHG,HYLD,HYMB,HYS,HYXU,IAF,IAI,IAK,IAT,IAU,IBCB,IBCC,IBCD,IBDA,IBDD,IBIO,IBND,ICF,ICH,ICI,ICN,ICOL,IDHB,IDHQ,IDI,IDLV,IDN,IDOG,IDU,IDV,IDX,IDXJ,IEC,IEF,IEFA,IEI,IELG,IEMG,IEO,IESM,IEV,IEZ,IF,IFMI,IG,IGC,IGE,IGEM,IGF,IGM,IGN,IGS,IGV,IHE,IHF,IHI,IHY,IJH,IJJ,IJK,IJR,IJS,IJT,ILB,ILF,ILTB,IMH,IMLP,IMO,IMUC,INCO,INDA,INDL,INFU,INKM,INO,INP,INR,INS,INUV,INXX,INY,IOIL,IOO,IOT,IPD,IPE,IPF,IPFF,IPK,IPN,IPS,IPU,IPW,IQDE,IQDF,IRT,IRY,ISL,ISR,ISRA,IST,ISTB,ITA,ITB,ITE,ITF,ITI,ITIP,ITM,ITOT,ITR,IVE,IVOG,IVOO,IVOV,IVV,IVW,IWB,IWC,IWD,IWF,IWL,IWM,IWN,IWO,IWP,IWR,IWS,IWV,IWW,IWX,IWY,IWZ,IXC,IXG,IXJ,IXN,IXP,IXUS,IYC,IYE,IYF,IYG,IYH,IYJ,IYK,IYLD,IYM,IYR,IYT,IYW,IYY,IYZ,JGBD,JGBS,JJA,JJC,JJE,JJG,JJM,JJN,JJS,JJT,JJU,JKD,JKE,JKF,JKG,JKH,JKI,JKJ,JKK,JKL,JNK,JO,JOB,JPNL,JPNS,JPP,JRS,JSC,JUNR,JXI,KBE,KBWB,KBWC,KBWD,KBWI,KBWR,KBWX,KBWY,KCE,KFYP,KIE,KLD,KME,KOL,KOLD,KORU,KORZ,KRE,KROO,KRS,KRU,KWT,KXI,LAG,LAQ,LATM,LBJ,LBND,LBY,LCI,LD,LEI,LEMB,LGEM,LGL,LGLV,LIT,LNG,LODE,LON,LOV,LPLT,LQD,LSC,LSG,LTL,LTPZ,LTS,LTS-A,LVL,LWC,MAB,MATH,MATL,MBB,MBG,MCF,MCHI,MCRO,MCZ,MDD,MDG.W,MDGN,MDM,MDW,MDY,MDYG,MDYV,MEA,MEET,MES,MGC,MGH,MGK,MGN,MGT,MGV,MHC,MHE,MHH,MHR-C,MHR-D,MHR-E,MIDU,MIDZ,MINC,MINT,MIW,MJC,MLN,MLPA,MLPG,MLPI,MLPJ,MLPL,MLPN,MLPX,MLPY,MMTM,MMV,MNA,MOAT,MOC,MOL,MOO,MORL,MORT,MOU,MSN,MSTX,MSXX,MTK,MTUM,MUAC,MUAD,MUAE,MUAF,MUAG,MUB,MUNI,MVF,MVG,MVV,MXA,MXC,MXI,MXN,MYY,MZA,MZZ,NAK,NASH,NAVB,NBH,NBO,NBW,NBY,NCB,NCQ,NCU,NEA,NEAR,NEN,NFO,NG,NGD,NGE,NGX,NHC,NHC-A,NHS,NIB,NJV,NKG,NKX,NKY,NLP,NLR,NMB,NML,NMZ,NNVC,NOG,NOM,NORW,NPN,NRK,NRO,NSPR,NSU,NTN,NTS,NUGT,NUJ,NVG,NVX,NVY,NXJ,NXK,NXM,NXZ,NY,NYC,NYF,NYH,NYV,NZF,NZH,OBT,OEF,OESX,OGEM,OGEN,OIH,OIL,OILZ,OLEM,OLO,ONEF,ONEK,ONN,ONP,ONVO,ORC,ORM,PAF,PAL,PALL,PBD,PBE,PBJ,PBM,PBP,PBS,PBW,PCC,PCEF,PCG-A,PCG-B,PCG-D,PCG-E,PCY,PCYG,PDN,PDO,PDP,PED,PEJ,PEK,PERM,PEY,PEZ,PFF,PFI,PFIG,PFM,PFXF,PGF,PGHY,PGJ,PGX,PHB,PHDG,PHF,PHO,PHYS,PICB,PICK,PID,PIE,PIN,PIO,PIP,PIZ,PJP,PKB,PKW,PLG,PLM,PLND,PLW,PLX,PMR,PPA,PPH,PPLT,PRB,PRF,PRK,PRN,PSJ,PSK,PSL,PSLV,PSP,PSQ,PSR,PST,PTF,PTH,PTM,PTN,PUI,PUW,PVI,PW,PWB,PWC,PWV,PWZ,PXE,PXF,PXH,PXI,PXJ,PXLC,PXLG,PXLV,PXMC,PXMG,PXMV,PXN,PXQ,PXR,PXSC,PXSG,PXSV,PYZ,PZA,PZD,PZG,PZI,PZT,QAI,QDEF,QDF,QDYN,QEH,QGEM,QID,QLD,QLTA,QLTB,QLTC,QMM,QMN,QQQE,QRM,QUAL,RALS,RAVI,RBL,RBY,RCD,REE,REED,REI,REK,REM,REMX,RETL,REW,REZ,RFG,RFV,RGI,RGRI,RHS,RIC,RIF,RING,RJA,RJI,RJN,RJZ,RKH,RLGT,RLY,RNN,ROLA,ROM,ROOF,ROX,RPG,RPV,RPX,RRGR,RSCO,RSP,RSX,RSXJ,RTH,RTL,RTM,RUSL,RUSS,RVM,RVNU,RVP,RWC,RWJ,RWK,RWL,RWM,RWO,RWR,RWW,RWX,RXD,RXI,RXL,RYE,RYF,RYH,RYJ,RYT,RYU,RZG,RZV,SAA,SAND,SARA,SBB,SBI,SBM,SBND,SCC,SCE-C,SCE-E,SCHA,SCHB,SCHC,SCHD,SCHE,SCHF,SCHG,SCHH,SCHM,SCHO,SCHP,SCHR,SCHV,SCHX,SCHZ,SCIF,SCIN,SCJ,SCO,SCPB,SCZ,SDD,SDIV,SDO-H,SDOG,SDOW,SDP,SDS,SDY,SDYL,SEA,SEB,SED,SEF,SFK,SGA,SGAR,SGB,SGG,SGOL,SH,SHM,SHN,SHV,SHY,SIF,SIJ,SIL,SILJ,SIM,SIVR,SJB,SJNK,SKF,SKK,SKY,SLI,SLV,SLVP,SLX,SLY,SLYG,SLYV,SMB,SMDD,SMH,SMIN,SMLV,SMMU,SMN,SMU,SNLN,SOIL,SOQ,SOXL,SOXS,SOYB,SPFF,SPGH,SPHB,SPHD,SPHQ,SPLV,SPPP,SPXH,SPXL,SPXS,SPXU,SPY,SPYG,SPYV,SRLN,SRS,SRTY,SSG,SSN,SSO,SST,SSY,STIP,STPP,STPZ,STRP,STS,SUB,SVBL,SVLC,SVT,SVXY,SYLD,SYN,SYRG,SZK,SZO,TAN,TAO,TAS,TAT,TBAR,TBF,TBT,TBX,TBZ,TCHI,TCX,TDH,TDN,TDTF,TDTT,TDV,TECL,TECS,TENZ,TFI,TGB,TGC,TGD,TGEM,THD,THHY,THM,THRK,TIK,TILT,TIP,TIPZ,TIS,TLH,TLO,TLR,TLT,TLTD,TLTE,TMF,TMP,TMV,TNA,TNDQ,TOF,TOK,TOTS,TPI,TPLM,TPS,TRND,TRNM,TRSK,TRT,TRX,TSH,TTFS,TTT,TUR,TUZ,TVIX,TVIZ,TWM,TWO.W,TWOK,TWTI,TXMD,TYBS,TYD,TYO,TZA,TZD,TZE,TZG,TZI,TZL,TZO,TZV,TZY,UAG,UAMY,UBC,UBG,UBM,UBN,UBR,UBT,UCC,UCI,UCO,UDN,UDNT,UDOW,UEC,UGA,UGAZ,UGL,UGLD,UHN,UKK,UKW,ULE,UMDD,UMX,UNG,UNL,UPG,UPRO,UPV,UPW,UQM,URA,URE,URG,URTH,URTY,URZ,USCI,USD,USL,USLV,USMV,USO,UST,USV,UTG,UUP,UUPT,UUU,UVE,UVG,UVT,UVU,UVXY,UWM,UWN,UWTI,UXI,UYG,UYM,VAW,VB,VBK,VBR,VCF,VCR,VDC,VDE,VEA,VEGA,VEGI,VEU,VFH,VFL,VGK,VGT,VGZ,VHC,VHT,VIG,VII,VIIX,VIIZ,VIOG,VIOO,VIOV,VIS,VIXM,VIXY,VKI,VMM,VNM,VNQ,VO,VOE,VOO,VOOG,VOOV,VOT,VOX,VPL,VPU,VQT,VRD,VSB,VSPY,VSR,VSS,VT,VTG,VTI,VTV,VUG,VV,VWO,VXF,VXX,VXZ,VYM,WDIV,WDTI,WEAT,WGA,WIP,WITE,WMCR,WMW,WPS,WREI,WRN,WTT,WYY,XAR,XBI,XES,XHB,XHE,XHS,XIV,XLB,XLE,XLF,XLG,XLI,XLK,XLP,XLU,XLV,XLY,XME,XMLV,XMPT,XOP,XOVR,XPH,XPL,XPP,XRA,XRT,XSD,XSLV,XSW,XTL,XTN,XVIX,XVZ,YANG,YAO,YCS,YINN,YMLI,YMLP,YXI,YYY,ZBB,ZIV,ZROZ,ZSL".split(",")));
		symbols.removeAll(amexList);
		System.out.println( "Total " +symbols.size()+ " symbols remaining after removing AMEX symbols." );
		System.out.println( "Symbols (after removing AMEX): " +symbols );
		
		
		if(true) return;
		
		final IntraDayDataProcessor iddp = new IntraDayDataProcessor();
		iddp.properties.setProperty("symbols", symbols.toString().replaceAll("\\[|\\]", ""));
		iddp.properties.setProperty("qualification.max.vxc.greater.than", properties.getProperty("qualification.max.vxc.greater.than"));
		iddp.properties.setProperty("qualification.max.vol.times.of.average.vol", properties.getProperty("qualification.max.vol.times.of.average.vol"));
		iddp.properties.setProperty("rpt.path", properties.getProperty("rpt.path"));
		iddp.properties.setProperty("rpt.path.for.qualified", properties.getProperty("rpt.path.for.qualified"));
		iddp.properties.setProperty("use.cache", properties.getProperty("use.cache"));
		
		iddp.main(args);
	}
}
