package com.stocks.util;

import java.io.BufferedReader;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.FileWriter;
import java.io.InputStreamReader;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.io.Serializable;
import java.math.BigDecimal;
import java.net.HttpURLConnection;
import java.net.URL;
import java.net.URLConnection;
import java.text.DateFormat;
import java.text.DecimalFormat;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.Calendar;
import java.util.Date;
import java.util.List;

import com.stocks.enums.Movement;
import com.stocks.standalone.IntraDayStructure;

public class Utility {
	final static DecimalFormat df = new DecimalFormat("###,###.##");
	final static DecimalFormat dfInteger = new DecimalFormat("###,###");
	
	public static final Long getDaysDifference(Date d1, Date d2){
		Long diff = d2.getTime() - d1.getTime();
		Long diffDays = diff / (24 * 60 * 60 * 1000);
		return diffDays;
	}
	
	public static String getContent(String sUrl) throws Exception {
		StringBuffer content = new StringBuffer();

		URL url = new URL(sUrl);
		final URLConnection urlConnection = url.openConnection();
		
		if( url.getProtocol().toLowerCase().equals("http") ){
			HttpURLConnection httpURLConnection = ((HttpURLConnection) urlConnection);
			httpURLConnection.setInstanceFollowRedirects(true);
//			httpURLConnection.setRequestProperty("Referer", "http://www.google.com/finance");
//			httpURLConnection.setRequestProperty("User-Agent", "Mozilla/5.0 (Windows NT 6.1; WOW64; rv:23.0) Gecko/20100101 Firefox/23.0");
		}
		
		urlConnection.setUseCaches(false);
		BufferedReader in = new BufferedReader(new InputStreamReader(urlConnection.getInputStream()));
		String inputLine;
		while ((inputLine = in.readLine()) != null) {
			content.append(inputLine).append("\n");
		}
		in.close();
		return content.toString();
	}
	
	public static void saveContent(String path, String content) throws Exception{
		FileWriter writer = new FileWriter(path);
		writer.append(content);
		writer.close();
	}
	
	public static void saveObjectToDisk(String absoluteFilePath, Serializable o) throws Exception{
		ObjectOutputStream oos = null;
		try{
			oos = new ObjectOutputStream( new FileOutputStream( absoluteFilePath ) );
			oos.writeObject(o);
		}
		finally{
			if( oos != null ){
				oos.close();
			}
		}
	}
	
	public static Serializable readObjectFromDisk(String absoluteFilePath) throws Exception{
		ObjectInputStream ois = null;
        try{
        	ois = new ObjectInputStream( new FileInputStream( absoluteFilePath ) );
        	return (Serializable) ois.readObject();
        }
        finally{
        	if( ois != null ){
        		ois.close();
        	}
        }
	}
	

	public static Double round(Double d){
		BigDecimal bd = new BigDecimal( d );
		bd = bd.setScale(2, BigDecimal.ROUND_HALF_UP);
		return bd.doubleValue();
	}

	public static boolean areDatesEqual(final Date d1, final Date d2){
		DateFormat df = new SimpleDateFormat("dd/MM/yyyy");
		final String s1 = df.format(d1);
		final String s2 = df.format(d2);
		return s1.equals(s2);
	}

	public static Date getDateFor(String str, String format) throws Exception {
		return new SimpleDateFormat(format).parse( str );
	}
	
	public static Date getDate(String str) throws Exception {
		return new SimpleDateFormat("MM/dd/yyyy").parse( str );
	}

	public static String getStrDate(Date dt, String format){
		return new SimpleDateFormat(format).format( dt );
	}
	
	public static String getStrDate(Date dt){
		return new SimpleDateFormat("MM/dd/yyyy").format( dt );
	}
	
	public static String getStrTime(Date dt){
		return new SimpleDateFormat("HH:mm:ss").format( dt );
	}
	
	public static long getDaysDiffBetween(Date olderDate, Date newerDate){
		long diff = newerDate.getTime() - olderDate.getTime();
		return Math.abs(diff / (1000 * 60 * 60 * 24));
	}
	
	public static String getFormattedNumber(Number number){
		return number != null ? df.format(number) : null;
	}

	public static String getFormattedInteger(Number number){
		return number != null ? dfInteger.format(number) : null;
	}
	
	/**
	 * Converts 1K to 1000, 1.2K to 1200 for K, M and B (thousands, millions and billions)
	 * @param strNum e.g 1K
	 * @return
	 */
	public static String convertFinancials(String strNum){
		String k = "000";
		String m = k + k;
		String b = m + k;
		String t = b + k;
		
		String result = strNum.toUpperCase().trim();

		if( result.endsWith("K") ){
			if( result.indexOf(".") != -1 ){
				int filler = (result.length()-2) - result.indexOf(".");
				k = k.substring(filler);
			}
			result = result.replace("K", k).replace(".", "");
		}else if( result.endsWith("M") ){
			if( result.indexOf(".") != -1 ){
				int filler = (result.length()-2) - result.indexOf(".");
				m = m.substring(filler);
			}
			result = result.replace("M", m).replace(".", "");
		}else if( result.endsWith("B") ){
			if( result.indexOf(".") != -1 ){
				int filler = (result.length()-2) - result.indexOf(".");
				b = b.substring(filler);
			}
			result = result.replace("B", b).replace(".", "");
		}else if( result.endsWith("T") ){
			if( result.indexOf(".") != -1 ){
				int filler = (result.length()-2) - result.indexOf(".");
				t = t.substring(filler);
			}
			result = result.replace("T", t).replace(".", "");
		} 
		
		//System.out.println( strNum +" --> "+result );
		return result;
	}
	
	public static Movement getCandleStickType(final IntraDayStructure ids){
		// Step1: Is Hammer-Like
		if( ids.getClose() > ids.getOpen() ){
			// Split OHLC into 3 parts
			final Double diffHighToClose = ids.getHigh() - ids.getClose();
			final Double body = ids.getClose() - ids.getOpen();
			final Double diffOpenToLow = ids.getOpen() - ids.getLow();
			if( body > diffHighToClose && body > diffOpenToLow ){ // If Body is largest
				// Buy
				return Movement.PUMP;
			}else if( diffHighToClose > diffOpenToLow ){ // If HighToClose is largest
				// Sell
				return Movement.DUMP;
			}else if( diffOpenToLow > diffHighToClose ){
				// Buy
				return Movement.PUMP;
			}else{
				return Movement.NONE;
			}
		}else if( ids.getClose() < ids.getOpen() ) { // Step2: Is Gravestone-Like
			// Split OHLC into 3 parts
			final Double diffHighToOpen = ids.getHigh() - ids.getOpen();
			final Double body = ids.getOpen() - ids.getClose();
			final Double diffCloseToLow = ids.getClose() - ids.getLow();
			if( body > diffHighToOpen && body > diffCloseToLow ){ // If Body is largest
				// Sell
				return Movement.DUMP;
			}else if( diffHighToOpen > diffCloseToLow ){ // If HighToOpen is largest
				// Sell
				return Movement.DUMP;
			}else if( diffCloseToLow > diffHighToOpen ){
				// Buy
				return Movement.PUMP;
			}else{
				return Movement.NONE;
			}
		}else{ // Step3: Other (DOJI)
			// Split OHLC into 3 parts
			final Double diffHighToOpen = ids.getHigh() - ids.getOpen();
			final Double body = ids.getOpen() - ids.getClose();
			final Double diffCloseToLow = ids.getClose() - ids.getLow();
			if( diffHighToOpen > diffCloseToLow ){ // If HighToOpen is largest
				// Sell
				return Movement.DUMP;
			}else if( diffCloseToLow > diffHighToOpen ){
				// Buy
				return Movement.PUMP;
			}else{
				return Movement.NONE;
			}
		}
	}
	
	/**
	 * 
	 * @return True of the current time is after 4:15PM, false otherwise
	 */
	public static boolean isAfter415(){
		Calendar c415 = Calendar.getInstance();
		c415.set( Calendar.HOUR, 4 );
		c415.set( Calendar.MINUTE, 15 );
		c415.set( Calendar.AM_PM, Calendar.PM );

		return Calendar.getInstance().after(c415);
	}
	
	public static void main(String args[]){
//		String arr[] = new String[]{"MMM", "ABB", "ABT", "ACL", "MO", "AMZN", "AXP", "AMGN", "AAPL", "AZN", "T", "AXAHY", "BBD", "STD", "BCS", "BRK.A", "BHP", "BBL", "BP", "BMY", "BTI", "CAJ", "CAT", "CVX", "LFC", "CHL", "SNP", "CSCO", "C", "CL", "CMCSA", "ABV", "COP", "CS", "CVS", "DB", "DT", "DEO", "EC", "LLY", "E", "XOM", "F", "FTE", "GE", "GSK", "GS", "GOOG", "HPQ", "HMC", "HBC", "INTC", "IBM", "JNJ", "JPM", "KFT", "LYG", "MCD", "MDT", "MRK", "MSFT", "MS", "NTT", "NOK", "NVS", "NVO", "DCM", "OXY", "ORCL", "PEP", "PTR", "PBR", "PFE", "PM", "QCOM", "RTP", "RY", "RDS.A", "SNY", "SAP", "SLB", "SI", "STO", "SU", "TGT", "TEF", "TEVA", "BNS", "BA", "KO", "HD", "PG", "DIS", "TD", "TOT", "USB", "UN", "UL", "UPS", "UTX", "VALE", "VZ", "V", "VOD", "WMT", "WFC", "WBK"};
//		String djia[] = new String[]{"MMM", "AA", "AXP", "T", "BAC", "BA", "CAT", "CVX", "CSCO", "KO", "DD", "XOM", "GE", "HPQ", "HD", "INTC", "IBM", "JNJ", "JPM", "KFT", "MCD", "MRK", "MSFT", "PFE", "PG", "TRV", "UTX", "VZ", "WMT", "DIS"};
//		List<String> arrList = new ArrayList(Arrays.asList("A,AA,AAN,AAON,AAP,AAPL,AAT,AAV,AAWW,AAXJ,AB,ABAX,ABB,ABBV,ABC,ABCO,ABFS,ABG,ABM,ABMD,ABT,ABV,ABX,ACAD,ACAS,ACAT,ACC,ACCL,ACCO,ACE,ACG,ACGL,ACH,ACHC,ACHN,ACI,ACIW,ACM,ACMP,ACN,ACO,ACOR,ACT,ACTG,ACTV,ACWI,ACWV,ACWX,ACXM,ADBE,ADI,ADM,ADP,ADS,ADSK,ADT,ADTN,ADVS,ADX,AEC,AEE,AEF,AEG,AEGN,AEGR,AEH,AEIS,AEL,AEM,AEO,AEP,AER,AES,AET,AF,AFCE,AFG,AFL,AFSI,AG,AGCO,AGG,AGI,AGII,AGIO,AGN,AGNC,AGNCP,AGO,AGQ,AGRO,AGU,AH,AHGP,AHL,AHS,AHT,AIG,AIMC,AIN,AINV,AIR,AIRM,AIT,AIV,AIXG,AIZ,AJG,AKAM,AKR,AKRX,AKS,AL,ALB,ALDW,ALE,ALEX,ALG,ALGN,ALGT,ALJ,ALK,ALKS,ALL,ALNY,ALOG,ALR,ALSN,ALTR,ALU,ALV,ALX,ALXN,AMAG,AMAP,AMAT,AMBC,AMCC,AMCX,AMD,AME,AMED,AMG,AMGN,AMH,AMJ,AMKR,AMLP,AMOV,AMP,AMRC,AMRE,AMRN,AMSF,AMSG,AMT,AMTD,AMWD,AMX,AMZN,AN,ANAT,ANDE,ANF,ANGI,ANH,ANN,ANR,ANSS,AOD,AOL,AON,AOS,APA,APAM,APC,APD,APEI,APH,APL,APO,APOG,APOL,APSA,APU,ARAY,ARB,ARCC,ARCO,ARCP,ARE,AREX,ARG,ARI,ARIA,ARII,ARLP,ARMH,ARNA,ARO,ARP,ARPI,ARR,ARRS,ARRY,ARTC,ARUN,ARW,ARX,ASBC,ASCMA,ASGN,ASH,ASIA,ASMI,ASML,ASNA,ASPS,ASR,ASTE,ASTX,ASX,ATE,ATHL,ATHN,ATI,ATK,ATLS,ATMI,ATML,ATNI,ATO,ATR,ATRO,ATRS,ATU,ATVI,ATW,AU,AUO,AUQ,AUXL,AUY,AV,AVA,AVAV,AVB,AVD,AVG,AVGO,AVIV,AVNR,AVP,AVT,AVX,AVY,AWAY,AWC,AWF,AWH,AWI,AWK,AWP,AWR,AXE,AXL,AXLL,AXP,AXS,AYI,AYR,AZN,AZO,AZPN,AZZ,B,BA,BAB,BAC,BAH,BAK,BAM,BANF,BANR,BAP,BAS,BAX,BBBY,BBCN,BBD,BBDO,BBEP,BBG,BBL,BBN,BBRY,BBT,BBVA,BBY,BC,BCA,BCC,BCE,BCEI,BCF,BCO,BCOR,BCPC,BCR,BCS,BCX,BDBD,BDC,BDJ,BDN,BDX,BEAM,BEAV,BECN,BEE,BEN,BEP,BERY,BFAM,BFK,BFR,BFS,BG,BGB,BGC,BGCP,BGG,BGR,BGS,BGX,BGY,BH,BHE,BHI,BHLB,BHP,BID,BIDU,BIG,BIIB,BIL,BIN,BIO,BIOS,BIP,BIT,BITA,BIV,BJRI,BK,BKCC,BKD,BKE,BKF,BKH,BKLN,BKS,BKU,BKW,BLC,BLDR,BLK,BLKB,BLL,BLMN,BLOX,BLT,BLUE,BLV,BLW,BLX,BMA,BMI,BMO,BMR,BMRN,BMS,BMY,BNCL,BND,BNNY,BNS,BOBE,BOE,BOFI,BOH,BOKF,BOXC,BP,BPFH,BPI,BPL,BPO,BPOP,BPT,BPY,BR,BRC,BRCD,BRCM,BRE,BRFS,BRKL,BRKR,BRKS,BRLI,BRO,BRS,BRY,BSAC,BSBR,BSFT,BSJF,BSMX,BSV,BSX,BT,BTE,BTT,BTU,BTZ,BUD,BV,BVN,BWA,BWC,BWLD,BWP,BWS,BWX,BX,BXMT,BXP,BXS,BYD,BYI,BZ,C,CA,CAB,CACC,CACI,CAE,CAF,CAG,CAH,CAJ,CAKE,CALM,CALX,CAM,CAMP,CAP,CAR,CASS,CASY,CAT,CATM,CATO,CATY,CAVM,CB,CBA,CBB,CBD,CBF,CBG,CBI,CBL,CBOE,CBPO,CBRL,CBS,CBSH,CBST,CBT,CBU,CCC,CCE,CCG,CCH,CCI,CCJ,CCK,CCL,CCMP,CCO,CCOI,CCU,CDE,CDNS,CDW,CE,CEA,CEB,CEC,CEL,CELG,CEM,CENX,CEO,CERN,CETV,CF,CFFN,CFN,CFNL,CFR,CFT,CFX,CG,CGG,CGNX,CGX,CHA,CHCO,CHD,CHDN,CHE,CHFC,CHH,CHI,CHK,CHKP,CHKR,CHL,CHMT,CHRW,CHS,CHSP,CHT,CHTR,CHU,CHUY,CHY,CI,CIB,CIE,CIEN,CIG,CII,CIM,CINF,CIR,CIT,CIU,CJES,CKH,CKP,CL,CLB,CLC,CLD,CLDX,CLF,CLGX,CLH,CLI,CLMT,CLNE,CLNY,CLP,CLR,CLS,CLV,CLVS,CLW,CLX,CM,CMA,CMC,CMCSA,CMCSK,CME,CMG,CMI,CMLP,CMLS,CMN,CMO,CMP,CMRE,CMS,CNA,CNC,CNCO,CNH,CNI,CNK,CNL,CNMD,CNO,CNP,CNQ,CNQR,CNS,CNSI,CNSL,CNW,CNX,CODE,CODI,COF,COG,COH,COHR,COKE,COL,COLB,COLE,COLM,CONN,COO,COP,COR,CORE,COST,COT,COTY,COV,CP,CPA,CPAC,CPB,CPF,CPHD,CPL,CPLA,CPLP,CPN,CPRT,CPSI,CPT,CPWR,CQB,CR,CRAY,CREE,CRH,CRI,CRK,CRL,CRM,CROX,CRR,CRRS,CRS,CRUS,CRVL,CRWN,CRZO,CS,CSC,CSCO,CSE,CSG,CSGP,CSGS,CSH,CSII,CSIQ,CSJ,CSL,CSOD,CSQ,CSRE,CST,CSTE,CSTM,CSU,CSWC,CSX,CTAS,CTB,CTBI,CTCM,CTCT,CTL,CTR,CTRP,CTRX,CTS,CTSH,CTXS,CUB,CUBE,CUK,CUZ,CVA,CVBF,CVC,CVCO,CVD,CVE,CVG,CVI,CVLT,CVRR,CVS,CVT,CVX,CVY,CW,CWB,CWEI,CWH,CWHN,CWT,CX,CXO,CXW,CY,CYBX,CYD,CYH,CYN,CYNO,CYOU,CYS,CYT,CZR,CZZ,D,DAC,DAL,DAN,DANG,DAR,DATA,DB,DBA,DBC,DBD,DCI,DCM,DCOM,DCT,DD,DDC,DDD,DDR,DDS,DE,DECK,DEG,DEI,DEL,DELL,DEM,DENN,DEO,DES,DF,DFS,DFT,DG,DGI,DGS,DGX,DHI,DHR,DHS,DHX,DIA,DIN,DIOD,DIS,DISCA,DISCK,DISH,DJP,DK,DKL,DKS,DLB,DLN,DLPH,DLR,DLS,DLTR,DLX,DMD,DMLP,DMND,DNB,DNKN,DNP,DNR,DO,DOLE,DON,DOOR,DORM,DOV,DOW,DOX,DPG,DPM,DPS,DPZ,DRC,DRE,DRH,DRI,DRII,DRIV,DRQ,DRU,DRYS,DSGX,DST,DSW,DSX,DTE,DTN,DTV,DUK,DV,DVA,DVN,DVY,DW,DWA,DWRE,DWX,DXCM,DXJ,DXPE,DY,DYAX,DYN,E,EA,EAT,EBAY,EBR,EBS,EC,ECA,ECHO,ECL,ECOL,ECOM,ECPG,ECYT,ED,EDD,EDE,EDG,EDIV,EDMC,EDR,EDT,EDU,EE,EEFT,EEM,EEMV,EEP,EEQ,EFA,EFAV,EFC,EFG,EFII,EFR,EFT,EFV,EFX,EGBN,EGHT,EGL,EGN,EGO,EGOV,EGP,EHTH,EIG,EIX,EJ,EL,ELD,ELGX,ELLI,ELN,ELNK,ELP,ELS,ELX,ELY,EMB,EMC,EME,EMES,EMLC,EMN,EMO,EMR,ENB,ENDP,ENH,ENI,ENL,ENR,ENS,ENSG,ENTG,ENV,EOC,EOG,EOPN,EOS,EPAM,EPAY,EPB,EPD,EPI,EPL,EPP,EPR,EPZM,EQIX,EQM,EQR,EQT,EQY,ERA,ERF,ERIC,ERIE,ERJ,EROC,ESC,ESD,ESE,ESGR,ESI,ESL,ESLT,ESRX,ESS,ESV,ETE,ETFC,ETG,ETH,ETJ,ETN,ETP,ETR,ETV,ETW,ETY,EV,EVAC,EVEP,EVER,EVHC,EVR,EVT,EVTC,EW,EWA,EWBC,EWC,EWH,EWI,EWJ,EWL,EWM,EWQ,EWS,EWT,EWU,EWW,EWX,EWY,EWZ,EXAM,EXAR,EXAS,EXC,EXEL,EXG,EXH,EXL,EXLP,EXLS,EXP,EXPD,EXPE,EXPO,EXPR,EXR,EXXI,EZA,EZCH,EZPW,EZU,F,FAF,FANG,FARO,FAS,FAST,FAZ,FB,FBC,FBHS,FBP,FBR,FBT,FCF,FCFS,FCH,FCN,FCNCA,FCS,FCX,FDL,FDML,FDN,FDO,FDP,FDS,FDX,FE,FEI,FEIC,FELE,FENG,FET,FEX,FEZ,FF,FFBC,FFC,FFG,FFIC,FFIN,FFIV,FGP,FHN,FI,FIBK,FICO,FIG,FII,FINL,FIO,FIRE,FIS,FISV,FITB,FIVE,FIX,FIZZ,FL,FLDM,FLEX,FLIR,FLO,FLOT,FLR,FLS,FLT,FLTX,FMBI,FMC,FMER,FMO,FMS,FMX,FN,FNB,FNF,FNFG,FNGN,FNP,FNSR,FNV,FOE,FOR,FORR,FOSL,FOX,FOXA,FOXF,FPO,FR,FRA,FRAN,FRC,FRED,FRGI,FRT,FRX,FSC,FSD,FSL,FSLR,FSM,FSRV,FSS,FST,FTI,FTK,FTNT,FTR,FUL,FULT,FUN,FVD,FWLT,FWM,FWRD,FXCM,FXD,FXG,FXH,FXI,G,GA,GAB,GAM,GAME,GAS,GB,GBCI,GBDC,GBL,GBLI,GBX,GCA,GCI,GCO,GD,GDOT,GDP,GDV,GDX,GDXJ,GE,GEF,GEL,GEO,GEOS,GES,GEVA,GFA,GFF,GFI,GG,GGAL,GGB,GGG,GGP,GHDX,GHL,GHY,GIB,GIII,GIL,GILD,GIM,GIMO,GIS,GIVN,GK,GLD,GLF,GLNG,GLOG,GLP,GLRE,GLT,GLW,GM,GMCR,GME,GMED,GMK,GMLP,GMT,GNC,GNRC,GNTX,GNW,GOGO,GOL,GOLD,GOOG,GOV,GPC,GPI,GPK,GPN,GPOR,GPS,GPX,GRA,GRAM,GRFS,GRMN,GRPN,GRT,GS,GSF,GSG,GSH,GSJ,GSK,GSM,GT,GTAT,GTI,GTLS,GTPPP,GTS,GTY,GVA,GVI,GWL,GWR,GWRE,GWW,GWX,GXC,GXP,GY,GZT,H,HAE,HAFC,HAIN,HAL,HALO,HAR,HAS,HAWK,HAYN,HBAN,HBANP,HBC,HBHC,HBI,HBM,HCA,HCBK,HCC,HCLP,HCN,HCP,HCS,HCSG,HD,HDB,HDS,HDV,HE,HEES,HEI,HELE,HEP,HERO,HES,HF,HFC,HGG,HGR,HHC,HHS,HI,HIBB,HIG,HII,HIMX,HITK,HITT,HIW,HIX,HK,HL,HLF,HLIT,HLS,HLSS,HLX,HMA,HMC,HME,HMIN,HMN,HMSY,HMY,HNI,HNP,HNT,HOG,HOLI,HOLX,HOMB,HON,HOS,HOT,HOV,HP,HPP,HPQ,HPS,HPT,HPTX,HPY,HQH,HR,HRB,HRC,HRG,HRL,HRS,HSC,HSH,HSIC,HSNI,HSP,HST,HSTM,HSY,HT,HTA,HTD,HTGC,HTH,HTHT,HTLD,HTS,HTSI,HTWR,HTZ,HUBG,HUM,HUN,HURN,HVT,HW,HWAY,HXL,HY,HYG,I,IACI,IAG,IART,IAT,IAU,IBA,IBB,IBKC,IBKR,IBM,IBN,IBOC,ICA,ICE,ICF,ICFI,ICGE,ICLR,ICON,ICPT,ICUI,IDA,IDCC,IDG,IDIX,IDTI,IDU,IDV,IDXX,IEF,IEI,IEP,IEV,IEX,IFF,IFGL,IFN,IGD,IGE,IGF,IGK,IGM,IGR,IGT,IGTE,IGV,IHG,IHS,IIJI,IILG,IIVI,IJH,IJJ,IJK,IJR,IJS,IJT,ILF,ILMN,IM,IMAX,IMGN,IMKTA,IMMU,IMPV,IN,INCY,IND,INDB,INFA,INFI,INFN,INFY,ING,INGR,ININ,INN,INSM,INSY,INT,INTC,INTU,INVN,INWK,INXN,INZ,IO,IOC,IOO,IOSP,IP,IPAR,IPCC,IPCM,IPE,IPG,IPGP,IPHS,IPI,IPXL,IR,IRBT,IRC,IRDM,IRE,IRET,IRF,IRM,IRWD,ISBC,ISCA,ISD,ISF,ISG,ISIL,ISIS,ISRG,IT,ITB,ITC,ITG,ITM,ITMN,ITOT,ITRI,ITT,ITUB,ITW,IVC,IVE,IVR,IVV,IVW,IVZ,IWB,IWC,IWD,IWF,IWM,IWN,IWO,IWP,IWR,IWS,IWV,IWW,IX,IXC,IXJ,IXN,IXP,IYE,IYF,IYG,IYH,IYJ,IYM,IYR,IYT,IYW,IYY,JACK,JAH,JAZZ,JBHT,JBL,JBLU,JBT,JCI,JCOM,JCP,JDSU,JE,JEC,JFR,JGT,JHI,JHX,JIVE,JJSF,JKHY,JLL,JNJ,JNK,JNPR,JNS,JNY,JOBS,JOE,JONE,JOSB,JOY,JPC,JPM,JPS,JQC,JSN,JWN,K,KALU,KAMN,KAR,KB,KBE,KBH,KBR,KCG,KDN,KEG,KELYA,KEP,KERX,KEX,KEY,KFN,KFRC,KFY,KGC,KIM,KKD,KKR,KLAC,KLIC,KMB,KMF,KMI,KMP,KMPR,KMR,KMT,KMX,KND,KNL,KNM,KNX,KO,KOF,KOG,KONG,KOP,KORS,KOS,KR,KRA,KRC,KRE,KRFT,KRG,KRNY,KRO,KS,KSS,KSU,KT,KTOS,KW,KWR,KXI,KYE,KYN,KYO,KYTH,L,LABL,LAD,LAG,LAMR,LANC,LAZ,LBTYA,LBTYK,LCC,LEA,LEAP,LECO,LEG,LEMB,LEN,LF,LFC,LFL,LFUS,LG,LGCY,LGF,LGND,LH,LHO,LIFE,LII,LIN,LINE,LINTA,LITB,LKFN,LKQ,LL,LLL,LLTC,LLY,LM,LMCA,LMNX,LMT,LNC,LNCE,LNCO,LNKD,LNN,LNT,LO,LOCK,LOGI,LOGM,LONG,LOPE,LORL,LOW,LPI,LPL,LPLA,LPNT,LPS,LPSN,LPX,LQD,LQDT,LRCX,LRE,LRN,LRY,LSCC,LSE,LSI,LSTR,LTC,LTD,LTM,LUK,LULU,LUV,LUX,LVB,LVLT,LVNTA,LVS,LXFT,LXK,LXP,LXRX,LXU,LYB,LYG,LYV,LZB,M,MA,MAA,MAC,MAIN,MAKO,MAN,MANH,MANT,MANU,MAR,MAS,MASI,MAT,MATW,MATX,MBB,MBFI,MBI,MBT,MCD,MCHI,MCHP,MCK,MCO,MCP,MCRL,MCRS,MCY,MD,MDAS,MDC,MDCA,MDCO,MDLZ,MDP,MDR,MDRX,MDSO,MDT,MDU,MDVN,MDY,MEAS,MEI,MELI,MEMP,MENT,MEOH,MET,MFA,MFB,MFC,MFG,MFRM,MGA,MGAM,MGEE,MGI,MGK,MGLN,MGM,MGRC,MGV,MHFI,MHK,MHLD,MHO,MHR,MIC,MIDD,MIL,MIN,MINI,MINT,MJN,MKC,MKL,MKSI,MKTG,MKTO,MKTX,MLG,MLHR,MLI,MLM,MLNX,MLPN,MLU,MM,MMC,MMLP,MMM,MMP,MMS,MMSI,MMU,MMYT,MNKD,MNRO,MNST,MNTA,MO,MOD,MOH,MOLX,MOLXA,MON,MOO,MORN,MOS,MOV,MOVE,MPC,MPEL,MPLX,MPW,MPWR,MR,MRC,MRH,MRK,MRO,MRTN,MRVL,MS,MSA,MSCC,MSCI,MSFT,MSG,MSI,MSK,MSM,MSTR,MT,MTB,MTD,MTDR,MTG,MTGE,MTH,MTL,MTN,MTOR,MTRN,MTSC,MTSI,MTU,MTW,MTX,MTZ,MU,MUB,MUC,MUI,MUR,MUSA,MUX,MW,MWA,MWE,MWIV,MWV,MWW,MX,MXIM,MYD,MYE,MYGN,MYI,MYL,N,NAT,NATI,NATL,NAV,NAVG,NBG,NBHC,NBIX,NBL,NBR,NBTB,NCI,NCLH,NCMI,NCR,NCS,NCT,NCV,NCZ,NDAQ,NDLS,NDSN,NDZ,NE,NEE,NEM,NEOG,NES,NETC,NEU,NEWP,NEWS,NFBK,NFG,NFJ,NFLX,NFX,NGG,NGL,NGLS,NGVC,NHI,NI,NICE,NIHD,NIO,NJ,NJR,NKA,NKE,NKTR,NL,NLSN,NLY,NM,NMA,NMFC,NMM,NMO,NMR,NNI,NNN,NOAH,NOC,NOK,NOV,NOW,NP,NPBC,NPI,NPM,NPO,NPP,NPSP,NQ,NQU,NR,NRF,NRG,NRGM,NRGY,NRP,NRZ,NS,NSC,NSH,NSIT,NSM,NSP,NSR,NTAP,NTCT,NTES,NTG,NTGR,NTI,NTK,NTL,NTRS,NTT,NU,NUAN,NUE,NUGT,NUS,NUV,NUVA,NVAX,NVDA,NVDQ,NVE,NVO,NVR,NVS,NWBI,NWE,NWL,NWLI,NWN,NWS,NWSA,NX,NXPI,NXST,NXTM,NYCB,NYLD,NYT,NYX,O,OAK,OAS,OB,OC,OCN,OCR,ODFL,ODP,OEF,OEH,OFC,OFG,OGE,OHI,OI,OIBR,OII,OILT,OIS,OKE,OKS,OLED,OLN,OMAB,OMC,OMCL,OMG,OMI,OMX,ONB,ONNN,ONTX,ONXX,OPEN,OPK,OPTR,ORA,ORAN,ORB,ORBK,ORCL,OREX,ORI,ORIG,ORIT,ORLY,OSIR,OSIS,OSK,OSTK,OTEX,OTTR,OUTR,OVTI,OWW,OXM,OXY,OZM,OZRK,P,PAA,PAAS,PAC,PACD,PACT,PACW,PAG,PALL,PANW,PAY,PAYX,PB,PBA,PBCT,PBF,PBH,PBI,PBR,PBT,PBY,PBYI,PCAR,PCG,PCH,PCL,PCLN,PCN,PCP,PCRX,PCY,PCYC,PDCE,PDCO,PDFS,PDH,PDI,PDLI,PDM,PDP,PDS,PDT,PEB,PEG,PEGA,PEI,PENN,PEO,PEP,PER,PETM,PF,PFE,PFF,PFG,PFMT,PFN,PFPT,PFS,PG,PGEM,PGF,PGH,PGR,PGX,PH,PHB,PHG,PHH,PHI,PHII,PHIIK,PHK,PHM,PHO,PHYS,PID,PII,PIR,PJC,PJP,PKD,PKE,PKG,PKI,PKW,PKX,PKY,PL,PLCE,PLCM,PLD,PLL,PLT,PLXS,PM,PMCS,PML,PMT,PMTC,PNC,PNFP,PNG,PNK,PNM,PNNT,PNR,PNRA,PNW,PNY,PODD,POL,POM,POOL,POR,POST,POT,POWI,POWL,PPC,PPG,PPL,PPLT,PPO,PPP,PPR,PPS,PPT,PRA,PRAA,PRE,PRF,PRFT,PRFZ,PRGO,PRGS,PRI,PRIM,PRLB,PRO,PRU,PRXL,PSA,PSB,PSE,PSEC,PSIX,PSMT,PSO,PSX,PSXP,PT,PTEN,PTLA,PTNR,PTP,PTR,PTY,PUK,PVD,PVG,PVH,PVR,PVTB,PWE,PWR,PWRD,PWV,PX,PXD,PXF,PZA,PZE,PZZA,Q,QCOM,QCOR,QDEL,QEP,QEPM,QGEN,QIHU,QIWI,QLD,QLGC,QLIK,QLYS,QQQ,QRE,QSII,QUAD,R,RAD,RAI,RALY,RAS,RATE,RAVN,RAX,RBA,RBC,RBCAA,RBS,RCAP,RCI,RCII,RCL,RCPT,RDA,RDC,RDEN,RDN,RDWR,RDY,RE,RECN,REG,REGN,REM,REMY,REN,RENN,RES,REV,REXX,RF,RFG,RFMD,RFP,RGA,RGC,RGLD,RGP,RGR,RGS,RH,RHI,RHP,RHT,RIG,RIO,RJET,RJF,RKT,RKUS,RL,RLGY,RLI,RLJ,RMBS,RMD,RNA,RNET,RNF,RNP,RNR,RNST,ROC,ROG,ROIC,ROK,ROL,ROLL,ROMA,ROP,ROSE,ROST,ROVI,ROYT,RP,RPAI,RPG,RPM,RPRX,RPT,RPTP,RPXC,RQI,RRC,RRD,RRGB,RRMS,RRTS,RS,RSE,RSG,RSO,RSP,RSTI,RSX,RTI,RTN,RUE,RUK,RUSHA,RUSHB,RVBD,RVT,RWO,RWR,RWT,RWX,RXN,RY,RYAAY,RYL,RYN,S,SA,SAFM,SAFT,SAH,SAI,SAIA,SALE,SAM,SAN,SANM,SAP,SAPE,SASR,SATS,SAVE,SB,SBAC,SBGI,SBGL,SBH,SBNY,SBR,SBRA,SBS,SBUX,SBY,SCBT,SCCO,SCG,SCHA,SCHB,SCHE,SCHF,SCHG,SCHL,SCHN,SCHV,SCHW,SCI,SCL,SCOR,SCPB,SCS,SCSC,SCSS,SCTY,SCU,SCVL,SCZ,SD,SDLP,SDR,SDRL,SDS,SDY,SE,SEAS,SEE,SEIC,SEM,SEMG,SEP,SF,SFD,SFG,SFI,SFL,SFLY,SFM,SFUN,SFY,SGEN,SGI,SGMO,SGMS,SGOL,SGY,SH,SHFL,SHG,SHI,SHLD,SHLM,SHM,SHO,SHOO,SHOS,SHPG,SHV,SHW,SHY,SI,SIAL,SID,SIG,SIGI,SINA,SIR,SIRI,SIRO,SIVB,SIX,SJI,SJM,SJNK,SJR,SJT,SJW,SKM,SKS,SKT,SKX,SKYW,SLAB,SLB,SLCA,SLF,SLG,SLGN,SLH,SLM,SLMAP,SLRC,SLV,SLW,SLXP,SM,SMCI,SMFG,SMG,SMH,SMI,SMLP,SMP,SMRT,SMS,SMTC,SN,SNA,SNCR,SNDK,SNE,SNH,SNHY,SNI,SNN,SNP,SNPS,SNTS,SNV,SNX,SNY,SO,SODA,SOHU,SON,SONC,SONS,SOR,SPB,SPF,SPG,SPH,SPIL,SPLK,SPLS,SPLV,SPN,SPNC,SPP,SPPI,SPR,SPRD,SPSC,SPW,SPWR,SPXU,SPY,SQI,SQM,SRC,SRCE,SRCL,SRE,SREV,SRLN,SRPT,SSD,SSI,SSL,SSNC,SSNI,SSO,SSP,SSRI,SSS,SSTK,SSW,SSYS,ST,STAG,STAN,STB,STBA,STBZ,STC,STCK,STE,STEI,STFC,STI,STIP,STJ,STKL,STLD,STM,STMP,STN,STNG,STNR,STO,STON,STPZ,STR,STRZA,STRZB,STSA,STT,STWD,STX,STZ,SU,SUB,SUI,SUNE,SUP,SUSP,SUSQ,SUSS,SVM,SVU,SWC,SWFT,SWHC,SWI,SWK,SWKS,SWM,SWN,SWU,SWX,SWY,SXC,SXCP,SXI,SXL,SXT,SYA,SYK,SYKE,SYMC,SYNA,SYNT,SYT,SYY,SZYM,T,TAC,TAHO,TAL,TAM,TAP,TARO,TASR,TAYC,TAYCP,TBBK,TBF,TBI,TBT,TC,TCAP,TCB,TCBI,TCK,TCO,TCP,TCRD,TD,TDC,TDF,TDG,TDS,TDW,TDY,TE,TECD,TECH,TEF,TEG,TEI,TEL,TEN,TEO,TEP,TER,TESO,TEVA,TEX,TFI,TFM,TFSL,TFX,TG,TGA,TGH,TGI,TGP,TGT,THC,THD,THG,THI,THO,THOR,THR,THRM,THRX,THS,TI,TIBX,TICC,TIF,TILE,TIP,TISI,TIVO,TJX,TK,TKC,TKR,TLAB,TLK,TLLP,TLM,TLP,TLT,TM,TMH,TMHC,TMK,TMO,TMS,TMUS,TMV,TNA,TNC,TNGO,TNH,TOK,TOL,TOO,TOT,TPC,TPL,TPRE,TPX,TQNT,TR,TRAK,TRC,TREX,TRGP,TRI,TRIP,TRK,TRLA,TRMB,TRMK,TRN,TRNX,TROW,TROX,TRP,TRQ,TRS,TRST,TRV,TRW,TS,TSCO,TSL,TSLA,TSM,TSN,TSO,TSRA,TSRO,TSRX,TSS,TSU,TTC,TTEC,TTEK,TTI,TTM,TTMI,TTS,TTWO,TU,TUES,TUMI,TUP,TV,TVE,TW,TWC,TWGP,TWI,TWO,TWTC,TWX,TX,TXI,TXN,TXRH,TXT,TXTR,TY,TYC,TYG,TYL,TYPE,TYY,TZA,UA,UACL,UAL,UAM,UAN,UBA,UBNT,UBP,UBS,UBSH,UBSI,UCBI,UDR,UEPS,UFCS,UFPI,UFS,UGI,UGP,UHAL,UHS,UHT,UIL,UIS,UL,ULTA,ULTI,UMBF,UMC,UMPQ,UN,UNF,UNFI,UNG,UNH,UNM,UNP,UNS,UNT,UNTD,UPL,UPS,URBN,URI,URS,USA,USAC,USB,USG,USM,USMV,USNA,USTR,UTEK,UTF,UTHR,UTIW,UTX,UUP,UVV,UWM,UYG,V,VAC,VAL,VALE,VAR,VAW,VB,VBK,VBR,VC,VCBI,VCI,VCIT,VCLK,VCLT,VCO,VCR,VCSH,VCV,VDC,VDE,VE,VEA,VECO,VET,VEU,VFC,VFH,VG,VGK,VGM,VGR,VGT,VHI,VHS,VHT,VIA,VIAB,VIG,VIP,VIPS,VIS,VIV,VIVO,VKQ,VLGEA,VLO,VLTR,VLY,VMC,VMI,VMW,VNET,VNO,VNQ,VNQI,VNR,VNTV,VO,VOD,VOE,VOLC,VOO,VOT,VOX,VOYA,VPFG,VPHM,VPL,VPRT,VPU,VQT,VR,VRA,VRNT,VRSK,VRSN,VRTS,VRTU,VRTX,VRX,VSAT,VSH,VSI,VSS,VTA,VTI,VTR,VTV,VUG,VV,VVC,VVR,VVUS,VWO,VXF,VXUS,VXX,VYM,VZ,WAB,WABC,WAC,WAFD,WAG,WAGE,WAIR,WAL,WASH,WAT,WBC,WBK,WBMD,WBS,WCC,WCG,WCN,WCRX,WD,WDAY,WDC,WDFC,WDR,WEC,WEN,WERN,WES,WETF,WEX,WF,WFC,WFM,WFT,WGL,WGO,WGP,WHR,WIBC,WIN,WIP,WIRE,WIT,WIW,WLH,WLK,WLL,WLP,WLT,WM,WMB,WMGI,WMK,WMS,WMT,WNC,WNR,WNS,WOOF,WOR,WPC,WPO,WPP,WPPGY,WPRT,WPT,WPX,WPZ,WR,WRB,WRD,WRE,WRI,WRLD,WSBC,WSFS,WSH,WSM,WSO,WST,WSTC,WTFC,WTI,WTM,WTR,WTS,WTW,WU,WWAV,WWD,WWE,WWW,WWWW,WX,WY,WYN,WYNN,X,XBI,XCO,XEC,XEL,XHB,XL,XLB,XLE,XLF,XLG,XLI,XLK,XLNX,XLP,XLS,XLV,XLY,XME,XOM,XON,XONE,XOOM,XPH,XPO,XRAY,XRS,XRX,XTEX,XTXI,XXIA,XYL,Y,YCS,YELP,YGE,YHOO,YNDX,YOKU,YPF,YUM,YY,YZC,Z,ZBRA,ZF,ZINC,ZION,ZMH,ZNGA,ZNH,ZQK,ZTR,ZTS,ZUMZ".split(",")));
//		List<String> amexList = new ArrayList(Arrays.asList("AAMC,AAU,ACCU,ACU,ACWV,ACY,ADGE,ADK,ADK-A,AE,AFK,AGA,AGEM,AGF,AGG,AGLS,AGOL,AGQ,AGX,AGZ,AIA,AJB,AKG,ALD,ALFA,ALN,ALTL,ALTV,AMCO,AMJ,AMLP,AMPE,AMPS,AMS,AMU,AND,ANGL,ANV,AOA,AOK,AOM,AOR,API,APP,APT,APTS,AQQ,ARGT,ARR.W,ASEA,ASM,ATL,ATMP,AUD,AUMN,AUNZ,AUSE,AVL,AWX,AXDI,AXHE,AXJL,AXN,AXTE,AXU,AXX,AYT,AZC,AZIA,BAA,BAB,BABS,BABZ,BAL,BBH,BBRC,BCM,BCV,BDCL,BDCS,BDD,BDR,BFOR,BFY,BHB,BHV,BIK,BIL,BIR-A,BIV,BIZD,BJK,BKF,BKJ,BKLN,BKR,BLE,BLJ,BLV,BND,BNO,BOIL,BOND,BONE,BPS,BQY,BRAF,BRAQ,BRAZ,BRD,BRF,BRN,BRXX,BRZS,BRZU,BSCD,BSCE,BSCF,BSCG,BSCH,BSCI,BSCJ,BSCK,BSCL,BSCM,BSJD,BSJE,BSJF,BSJG,BSJH,BSJI,BSJJ,BSJK,BSV,BTG,BTI,BTN,BTX,BUND,BUNT,BVX,BWL.A,BWX,BWZ,BXE,BZC,BZF,BZM,BZQ,CAD,CAFE,CAK,CANE,CAPE,CAW,CBND,CCA,CCF,CCXE,CDY,CEF,CEMB,CEP,CET,CEV,CEW,CFD,CFP,CFT,CGR,CGW,CH,CHEP,CHGS,CHIE,CHII,CHIM,CHIQ,CHIX,CHLC,CHOC,CHXX,CIK,CIU,CIX,CLM,CLY,CMBS,CMDT,CMF,CMFO,CMT,CNDA,CNPF,CNR,CNY,COBO,COLX,COPX,CORN,CORP,COVR,COW,CPHI,CPI,CQP,CQQQ,CRBQ,CRF,CRM.W,CRMD,CROC,CROP,CRUD,CRV,CRVP,CSCB,CSCR,CSD,CSJ,CSLS,CSM,CSMA,CSMB,CSMN,CTF,CTO,CTP,CUO,CUR,CURE,CUT,CVM,CVOL,CVR,CVU,CVY,CWB,CWI,CXA,CXM,CYB,CZA,DAG,DBA,DBB,DBBR,DBC,DBE,DBEF,DBEM,DBGR,DBIZ,DBJP,DBO,DBP,DBS,DBU,DBV,DCNG,DDM,DDP,DEF,DEJ,DEM,DES,DEW,DFE,DFF,DFJ,DGAZ,DGL,DGLD,DGP,DGS,DGSE,DGT,DGZ,DHS,DHY,DIA,DIG,DIM,DIRT,DIT,DIV,DJCI,DJP,DLA,DLBL,DLBS,DLN,DLS,DMF,DNL,DNN,DNO,DOD,DOG,DOIL,DOL,DON,DOO,DPK,DPU,DPW,DRN,DRR,DRV,DRW,DSI,DSLV,DSS,DSUM,DTD,DTH,DTN,DTO,DTUS,DTYL,DTYS,DUG,DUST,DVHI,DVY,DVYA,DVYE,DVYL,DWAS,DWM,DWTI,DWX,DXD,DXJ,DXR,DYY,DZK,DZZ,EAD,EAPS,EBND,ECF,ECH,ECNS,ECON,EDC,EDEN,EDIV,EDV,EDZ,EEB,EEH,EEHB,EELV,EEM,EEMS,EEMV,EES,EET,EEV,EFA,EFAV,EFG,EFNL,EFO,EFU,EFV,EFZ,EGAS,EGI,EGPT,EIA,EIDO,EIM,EIO,EIP,EIRL,EIS,EIV,ELD,ELLO,ELMD,EMAN,EMB,EMCD,EMCR,EMDD,EMDG,EMFT,EMHD,EMHY,EMI,EMJ,EMLC,EMLP,EMT,EMXX,ENGN,ENOR,ENX,ENY,ENZL,EOX,EPHE,EPI,EPM,EPM-A,EPOL,EPP,EPS,EPU,EPV,EQL,ERB,ERC,ERH,ERO,ERUS,ERX,ERY,ESP,ESR,ESTE,ETAK,ETF,ETUA,ETUB,EUFX,EUM,EUO,EUSA,EVBN,EVI,EVJ,EVK,EVM,EVO,EVP,EVV,EVX,EVY,EWA,EWAS,EWC,EWCS,EWD,EWEM,EWG,EWGS,EWH,EWHS,EWI,EWJ,EWK,EWL,EWM,EWN,EWO,EWP,EWQ,EWRI,EWRM,EWRS,EWS,EWSS,EWT,EWU,EWUS,EWV,EWW,EWX,EWY,EWZ,EWZS,EXE,EXI,EXT,EZA,EZJ,EZM,EZU,FAB,FAD,FAN,FAS,FAUS,FAX,FAZ,FBG,FBT,FCA,FCAN,FCG,FCO,FCSC,FDD,FDL,FDM,FDN,FDT,FDTS,FEEU,FEM,FEMS,FEN,FEP,FEU,FEX,FEZ,FFR,FGD,FGEM,FGM,FHK,FIEU,FIGY,FINU,FINZ,FIVZ,FIW,FJP,FKU,FLAG,FLM,FLN,FLOT,FLRN,FLTR,FM,FMF,FMK,FNDA,FNDB,FNDC,FNDE,FNDF,FNDX,FNI,FNIO,FNK,FNX,FNY,FOL,FORX,FPA,FPE,FPP,FPP.W,FPX,FRAK,FRD,FRI,FRN,FRS,FSE,FSG,FSI,FSP,FSZ,FTA,FTC,FTF,FTY,FU,FUD,FVD,FVI,FVL,FWDB,FXA,FXB,FXC,FXD,FXE,FXF,FXG,FXH,FXI,FXL,FXN,FXO,FXP,FXR,FXS,FXU,FXY,FXZ,FYC,FYT,FYX,GAF,GAL,GASL,GASX,GAZ,GBB,GBF,GBR,GCC,GCE,GDAY,GDX,GDXJ,GEX,GGEM,GGGG,GGN,GGN-B,GGOV,GHM,GHYG,GIG,GII,GLD,GLDX,GLL,GLO,GLOW,GLQ,GLTR,GLU,GLU-A,GLV,GMF,GML,GMM,GMO,GNAT,GNR,GORO,GOVT,GPL,GRC,GREK,GRES,GRF,GRH,GRH-C,GRI,GRU,GSB,GSC,GSG,GSP,GSRA,GSS,GST,GST-A,GSV,GSY,GTAA,GTE,GTIP,GTT,GTU,GUNR,GUR,GURU,GV,GVI,GVP,GWL,GWX,GXC,GXF,GXG,GYLD,HAO,HAP,HDG,HDGE,HDGI,HDV,HEB,HECO,HEDJ,HGEM,HGI,HH,HILO,HLM.P,HNW,HSPX,HTM,HUSA,HUSE,HVPW,HYD,HYEM,HYG,HYHG,HYLD,HYMB,HYS,HYXU,IAF,IAI,IAK,IAT,IAU,IBCB,IBCC,IBCD,IBDA,IBDD,IBIO,IBND,ICF,ICH,ICI,ICN,ICOL,IDHB,IDHQ,IDI,IDLV,IDN,IDOG,IDU,IDV,IDX,IDXJ,IEC,IEF,IEFA,IEI,IELG,IEMG,IEO,IESM,IEV,IEZ,IF,IFMI,IG,IGC,IGE,IGEM,IGF,IGM,IGN,IGS,IGV,IHE,IHF,IHI,IHY,IJH,IJJ,IJK,IJR,IJS,IJT,ILB,ILF,ILTB,IMH,IMLP,IMO,IMUC,INCO,INDA,INDL,INFU,INKM,INO,INP,INR,INS,INUV,INXX,INY,IOIL,IOO,IOT,IPD,IPE,IPF,IPFF,IPK,IPN,IPS,IPU,IPW,IQDE,IQDF,IRT,IRY,ISL,ISR,ISRA,IST,ISTB,ITA,ITB,ITE,ITF,ITI,ITIP,ITM,ITOT,ITR,IVE,IVOG,IVOO,IVOV,IVV,IVW,IWB,IWC,IWD,IWF,IWL,IWM,IWN,IWO,IWP,IWR,IWS,IWV,IWW,IWX,IWY,IWZ,IXC,IXG,IXJ,IXN,IXP,IXUS,IYC,IYE,IYF,IYG,IYH,IYJ,IYK,IYLD,IYM,IYR,IYT,IYW,IYY,IYZ,JGBD,JGBS,JJA,JJC,JJE,JJG,JJM,JJN,JJS,JJT,JJU,JKD,JKE,JKF,JKG,JKH,JKI,JKJ,JKK,JKL,JNK,JO,JOB,JPNL,JPNS,JPP,JRS,JSC,JUNR,JXI,KBE,KBWB,KBWC,KBWD,KBWI,KBWR,KBWX,KBWY,KCE,KFYP,KIE,KLD,KME,KOL,KOLD,KORU,KORZ,KRE,KROO,KRS,KRU,KWT,KXI,LAG,LAQ,LATM,LBJ,LBND,LBY,LCI,LD,LEI,LEMB,LGEM,LGL,LGLV,LIT,LNG,LODE,LON,LOV,LPLT,LQD,LSC,LSG,LTL,LTPZ,LTS,LTS-A,LVL,LWC,MAB,MATH,MATL,MBB,MBG,MCF,MCHI,MCRO,MCZ,MDD,MDG.W,MDGN,MDM,MDW,MDY,MDYG,MDYV,MEA,MEET,MES,MGC,MGH,MGK,MGN,MGT,MGV,MHC,MHE,MHH,MHR-C,MHR-D,MHR-E,MIDU,MIDZ,MINC,MINT,MIW,MJC,MLN,MLPA,MLPG,MLPI,MLPJ,MLPL,MLPN,MLPX,MLPY,MMTM,MMV,MNA,MOAT,MOC,MOL,MOO,MORL,MORT,MOU,MSN,MSTX,MSXX,MTK,MTUM,MUAC,MUAD,MUAE,MUAF,MUAG,MUB,MUNI,MVF,MVG,MVV,MXA,MXC,MXI,MXN,MYY,MZA,MZZ,NAK,NASH,NAVB,NBH,NBO,NBW,NBY,NCB,NCQ,NCU,NEA,NEAR,NEN,NFO,NG,NGD,NGE,NGX,NHC,NHC-A,NHS,NIB,NJV,NKG,NKX,NKY,NLP,NLR,NMB,NML,NMZ,NNVC,NOG,NOM,NORW,NPN,NRK,NRO,NSPR,NSU,NTN,NTS,NUGT,NUJ,NVG,NVX,NVY,NXJ,NXK,NXM,NXZ,NY,NYC,NYF,NYH,NYV,NZF,NZH,OBT,OEF,OESX,OGEM,OGEN,OIH,OIL,OILZ,OLEM,OLO,ONEF,ONEK,ONN,ONP,ONVO,ORC,ORM,PAF,PAL,PALL,PBD,PBE,PBJ,PBM,PBP,PBS,PBW,PCC,PCEF,PCG-A,PCG-B,PCG-D,PCG-E,PCY,PCYG,PDN,PDO,PDP,PED,PEJ,PEK,PERM,PEY,PEZ,PFF,PFI,PFIG,PFM,PFXF,PGF,PGHY,PGJ,PGX,PHB,PHDG,PHF,PHO,PHYS,PICB,PICK,PID,PIE,PIN,PIO,PIP,PIZ,PJP,PKB,PKW,PLG,PLM,PLND,PLW,PLX,PMR,PPA,PPH,PPLT,PRB,PRF,PRK,PRN,PSJ,PSK,PSL,PSLV,PSP,PSQ,PSR,PST,PTF,PTH,PTM,PTN,PUI,PUW,PVI,PW,PWB,PWC,PWV,PWZ,PXE,PXF,PXH,PXI,PXJ,PXLC,PXLG,PXLV,PXMC,PXMG,PXMV,PXN,PXQ,PXR,PXSC,PXSG,PXSV,PYZ,PZA,PZD,PZG,PZI,PZT,QAI,QDEF,QDF,QDYN,QEH,QGEM,QID,QLD,QLTA,QLTB,QLTC,QMM,QMN,QQQE,QRM,QUAL,RALS,RAVI,RBL,RBY,RCD,REE,REED,REI,REK,REM,REMX,RETL,REW,REZ,RFG,RFV,RGI,RGRI,RHS,RIC,RIF,RING,RJA,RJI,RJN,RJZ,RKH,RLGT,RLY,RNN,ROLA,ROM,ROOF,ROX,RPG,RPV,RPX,RRGR,RSCO,RSP,RSX,RSXJ,RTH,RTL,RTM,RUSL,RUSS,RVM,RVNU,RVP,RWC,RWJ,RWK,RWL,RWM,RWO,RWR,RWW,RWX,RXD,RXI,RXL,RYE,RYF,RYH,RYJ,RYT,RYU,RZG,RZV,SAA,SAND,SARA,SBB,SBI,SBM,SBND,SCC,SCE-C,SCE-E,SCHA,SCHB,SCHC,SCHD,SCHE,SCHF,SCHG,SCHH,SCHM,SCHO,SCHP,SCHR,SCHV,SCHX,SCHZ,SCIF,SCIN,SCJ,SCO,SCPB,SCZ,SDD,SDIV,SDO-H,SDOG,SDOW,SDP,SDS,SDY,SDYL,SEA,SEB,SED,SEF,SFK,SGA,SGAR,SGB,SGG,SGOL,SH,SHM,SHN,SHV,SHY,SIF,SIJ,SIL,SILJ,SIM,SIVR,SJB,SJNK,SKF,SKK,SKY,SLI,SLV,SLVP,SLX,SLY,SLYG,SLYV,SMB,SMDD,SMH,SMIN,SMLV,SMMU,SMN,SMU,SNLN,SOIL,SOQ,SOXL,SOXS,SOYB,SPFF,SPGH,SPHB,SPHD,SPHQ,SPLV,SPPP,SPXH,SPXL,SPXS,SPXU,SPY,SPYG,SPYV,SRLN,SRS,SRTY,SSG,SSN,SSO,SST,SSY,STIP,STPP,STPZ,STRP,STS,SUB,SVBL,SVLC,SVT,SVXY,SYLD,SYN,SYRG,SZK,SZO,TAN,TAO,TAS,TAT,TBAR,TBF,TBT,TBX,TBZ,TCHI,TCX,TDH,TDN,TDTF,TDTT,TDV,TECL,TECS,TENZ,TFI,TGB,TGC,TGD,TGEM,THD,THHY,THM,THRK,TIK,TILT,TIP,TIPZ,TIS,TLH,TLO,TLR,TLT,TLTD,TLTE,TMF,TMP,TMV,TNA,TNDQ,TOF,TOK,TOTS,TPI,TPLM,TPS,TRND,TRNM,TRSK,TRT,TRX,TSH,TTFS,TTT,TUR,TUZ,TVIX,TVIZ,TWM,TWO.W,TWOK,TWTI,TXMD,TYBS,TYD,TYO,TZA,TZD,TZE,TZG,TZI,TZL,TZO,TZV,TZY,UAG,UAMY,UBC,UBG,UBM,UBN,UBR,UBT,UCC,UCI,UCO,UDN,UDNT,UDOW,UEC,UGA,UGAZ,UGL,UGLD,UHN,UKK,UKW,ULE,UMDD,UMX,UNG,UNL,UPG,UPRO,UPV,UPW,UQM,URA,URE,URG,URTH,URTY,URZ,USCI,USD,USL,USLV,USMV,USO,UST,USV,UTG,UUP,UUPT,UUU,UVE,UVG,UVT,UVU,UVXY,UWM,UWN,UWTI,UXI,UYG,UYM,VAW,VB,VBK,VBR,VCF,VCR,VDC,VDE,VEA,VEGA,VEGI,VEU,VFH,VFL,VGK,VGT,VGZ,VHC,VHT,VIG,VII,VIIX,VIIZ,VIOG,VIOO,VIOV,VIS,VIXM,VIXY,VKI,VMM,VNM,VNQ,VO,VOE,VOO,VOOG,VOOV,VOT,VOX,VPL,VPU,VQT,VRD,VSB,VSPY,VSR,VSS,VT,VTG,VTI,VTV,VUG,VV,VWO,VXF,VXX,VXZ,VYM,WDIV,WDTI,WEAT,WGA,WIP,WITE,WMCR,WMW,WPS,WREI,WRN,WTT,WYY,XAR,XBI,XES,XHB,XHE,XHS,XIV,XLB,XLE,XLF,XLG,XLI,XLK,XLP,XLU,XLV,XLY,XME,XMLV,XMPT,XOP,XOVR,XPH,XPL,XPP,XRA,XRT,XSD,XSLV,XSW,XTL,XTN,XVIX,XVZ,YANG,YAO,YCS,YINN,YMLI,YMLP,YXI,YYY,ZBB,ZIV,ZROZ,ZSL".split(",")));
//		arrList.removeAll(amexList);
//		System.out.println( arrList );
/*
		convertFinancials( "1.2K" );
		convertFinancials( "1.22K" );
		convertFinancials( "1.222K" );
		convertFinancials( "1.3m" );
		convertFinancials( "1.33m" );
		convertFinancials( "1.5b" );
		convertFinancials( "1.55b" );
		convertFinancials( "3k" );
		convertFinancials( "3m" );
		convertFinancials( "3b" );
		convertFinancials( "3.1t" );
*/
		
/*		
		System.out.println( getFormattedNumber( null ) );
		System.out.println( getFormattedNumber( 0.00 ) );
		System.out.println( getFormattedNumber( 123456789.50 ) );
		System.out.println( getFormattedNumber( 123456789012.00 ) );
*/
	}
}
